#!/usr/bin/env bash

REAL_PATH=$(perl -MCwd='abs_path' -e 'printf "%s", abs_path("'"$0"'")' | xargs dirname)
source $REAL_PATH/config

printf "$PRINTFMT" "Breaking up 'Other emails' field: "
time (sub_newline "" "$REAL_PATH/.data/join-components/contact-join.src.csv" | sort -r | uniq | vstack -d "," 14 $(seq -s " " 1 11) 13 |
	paste -d "," - <( sub_newline "" "$REAL_PATH/.data/join-components/contact-join.src.csv" |
	sort -r | uniq | vstack -d "," 12  | tail +2 | sed 's/"//g' | 
	pad_commas "Other emails") > "$REAL_PATH/.data/join-components/contact-join.csv")

printf "$PRINTFMT" "Counting duplicate emails and saving to file: "
time (vstack -u $(seq -s " " 10 12) $(seq -s " " 14 17) < <(tail +2 $REAL_PATH/.data/join-components/contact-join.csv) | 
	sort | uniq -c | sort -rn | tail +2 | sed "s/^ *//; s/ /,/" | vstack -d "," 2 1 > "$REAL_PATH/tmp" && 
	cat <(echo "Unique Email,Number of Records") "$REAL_PATH/tmp" > "$REAL_PATH/.data/duplicate-email.csv")
	
printf "$PRINTFMT" "Counting duplicate names and saving to file: "
time (vstack -d " " 6 8 < <(tail +2 "$REAL_PATH/.data/join-components/contact-join.csv") | 
	sort | uniq -c | sort -rn | sed $'s/^ *//; s/"//g; s/,//g; s/ /\t/' | vstack -F $'\t' -d "," 2 1 > "$REAL_PATH/tmp" && 
	cat <(echo "Unique Name,Number of Records") "$REAL_PATH/tmp" > "$REAL_PATH/.data/duplicate-name.csv")

printf "$PRINTFMT" "Appending duplicate email information to list: "
time (vlookup -m "$REAL_PATH/.data/duplicate-email.csv" 1 $(seq -s " " 10 12) $(seq -s " " 14 17) < <(tail +2 "$REAL_PATH/.data/join-components/contact-join.csv") > "$REAL_PATH/tmp" && 
	paste -d "," - "$REAL_PATH/tmp" < <(tail +2 "$REAL_PATH/.data/join-components/contact-join.csv") > "$REAL_PATH/.data/counted-contact.1.csv")

printf "$PRINTFMT" "Appending duplicate name information to list: "
time (vlookup -m "$REAL_PATH/.data/duplicate-name.csv" 1 1 < <(vstack -d " " 6 8 < <(tail +2 "$REAL_PATH/.data/join-components/contact-join.csv") | 
	sed 's/"//g; s/,//g') > "$REAL_PATH/tmp" && 
	paste -d "," - "$REAL_PATH/tmp" < "$REAL_PATH/.data/counted-contact.1.csv" |
	sort -t , -k 1,1 > "$REAL_PATH/.data/counted-contact.2.csv")

printf "$PRINTFMT" "Join account info: "
time (sub_newline "$REAL_PATH/.data/join-components/acct-join.src.csv" | sort -r | uniq |
	tail +2 | sort -t , -k 1,1 > "$REAL_PATH/.data/join-components/acct-join.csv" &&
	join -t , -a 1 "$REAL_PATH/.data/counted-contact.2.csv" "$REAL_PATH/.data/join-components/acct-join.csv" |
	sort -t , -k 2,2 > "$REAL_PATH/.data/counted-contact-acct.csv")

printf "$PRINTFMT" "Join affiliation data with account info: "
time (sub_newline "$REAL_PATH/.data/join-components/affiliation-join.src.csv" | sort -r | uniq | tail +2 | sort -t , -k 2,2 |
	join -t , -1 2 - "$REAL_PATH/.data/join-components/acct-join.csv" > "$REAL_PATH/.data/join-components/affiliation.join.csv")

printf "$PRINTFMT" "Join affiliation data to contact list: "
time (sort -t , -k 2,2 "$REAL_PATH/.data/join-components/affiliation.join.csv" | 
	join -t , -a 1 -j 2 "$REAL_PATH/.data/counted-contact-acct.csv" - |
	pad_commas > "$REAL_PATH/.data/counted-contact-acct-affiliation.csv")

printf "$PRINTFMT" "Add appropriate headers: "
time (cat <(echo "$CONTACT_HEADERS") "$REAL_PATH/.data/counted-contact.2.csv" > "$REAL_PATH/tmp" && 
	mv "$REAL_PATH/tmp" "$REAL_PATH/.data/counted-contact.csv" &&
	cat <(echo "$CONTACT_ACCT_HEADERS") "$REAL_PATH/.data/counted-contact-acct.csv" > "$REAL_PATH/tmp" && 
	mv "$REAL_PATH/tmp" "$REAL_PATH/.data/counted-contact-acct.csv" &&
	cat <(echo "$CONTACT_ACCT_AFF_HEADERS") "$REAL_PATH/.data/counted-contact-acct-affiliation.csv" > "$REAL_PATH/tmp" &&
	mv "$REAL_PATH/tmp" "$REAL_PATH/.data/counted-contact-acct-affiliation.csv")
