#!/usr/bin/env bash

TIMEFORMAT=$'%Rs'
SPACING=80
PRINTFMT="%-${SPACING}s"
HEADERS=(
	"Account ID"
	"Contact ID"
	"Confirmation of receiving updates"
	"Newsletter"
	"Salutation"
	"First Name"
	"Middle Name"
	"Last Name"
	"Congregation"
	"Personal Email"
	"Alternate Email"
	"Work Email"
	"Phone"
	"Other emails 1"
	"Other emails 2"
	"Other emails 3"
	"Other emails 4"
	"Email Count"
	"Name Count"
	"Account Name"
	"Type"
	"Billing City"
	"Billing Street"
	"Billing State"
	"Billing Zip"
	"Billing Country"
	"Affiliation Account ID"
	"Affiliation ID"
	"Primary"
	"Role"
	"Affiliation Name"
	"Affiliation Type"
	"Affiliation City"
	"Affiliation Street"
	"Affiliation State"
	"Affiliation Zip"
	"Affiliation Country"
)

# IFS tricks found here:
# https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-a-bash-array-into-a-delimited-string
CONTACT_HEADERS=$(printf "%s," "${HEADERS[@]::19}") && CONTACT_HEADERS=${CONTACT_HEADERS%,}
CONTACT_ACCT_HEADERS=$(printf "%s," "${HEADERS[@]::26}") && CONTACT_ACCT_HEADERS=${CONTACT_ACCT_HEADERS%,}
CONTACT_ACCT_AFF_HEADERS=$(printf "%s," "${HEADERS[@]}") && CONTACT_ACCT_AFF_HEADERS=${CONTACT_ACCT_AFF_HEADERS%,}
