#!/usr/bin/env bash

REAL_PATH=$(perl -MCwd='abs_path' -e 'printf "%s", abs_path("'"$0"'")' | xargs dirname)

declare -a job_stack
declare -a job_state

job_state=(
	"JobComplete"
	"InProgress"
	"UploadComplete"
	"Aborted"
	"Failed"
)


init_token() {
	local SF_TOKEN=$(sf org display -o jaselg@reform.org.il --json | jq -j '.result.accessToken')
	sed -i "/SF_TOKEN/s/=.*/=$SF_TOKEN/" .env
}

hrs_elapsed() {
	local seconds_elapsed=$(( $2 - $1 ))
	echo $(( seconds_elapsed / 3600 ))
}


# Refresh token if inactive for over two hours
if (( $(hrs_elapsed $(stat --printf "%X" .env) $(date +"%s")) > 2 )); then
	source $REAL_PATH/.env
	printf "$PRINTFMT" "API Token expired. Refreshing: "
	time init_token	
else
	source $REAL_PATH/.env
fi

# Loop over SOQL queries in queries dir, create jobs and push job ids to stack
# for query in queries/*.soql; do
	# printf "$PRINTFMT" "Creating query job with $query: " 
	# time curr_id=$($REAL_PATH/create_query.pl $SF_TOKEN $query)
	# job_stack+=$curr_id
# done

job_stack=(
	"750Tw00000dk6lWIAQ"
	"750Tw00000djy9fIAA"
	"750Tw00000djtukIAA"
)

# Check each id in stack and test exit code to determine whether to download results
while true; do
	limit=${#job_stack[@]}

	for (( i=0; i < $limit; i++ )); do
		printf "$PRINTFMT" "Checking job ${job_stack[$i]}: "
		time name=$($REAL_PATH/check_status.pl $SF_TOKEN ${job_stack[$i]}) 
		exit_code=$?

		echo -e "\tJob state is ${job_state[$exit_code]}"  
		if [ $exit_code -eq 0 ]; then
			printf "\t${PRINTFMT/$SPACING/$(( SPACING - 8 ))}" "Downloading $name query:"
			time unset 'job_stack[i]'
		fi
	done

	if [ ${#job_stack[@]} -eq 0 ]; then
		break
	fi

	# Still jobs in the stack. Remove empty indices and sleep before next check
	temp_arr=( ${job_stack[@]} ) && job_stack=( ${temp_arr[@]} )
	sleep 3
done

echo "Broke out of loop."
