#!/usr/bin/env bash

REAL_PATH=$(perl -MCwd='abs_path' -e 'printf "%s", abs_path("'"$0"'")' | xargs dirname)
source $REAL_PATH/config
SLEEP=4.5

init_token() {
	local SF_TOKEN=$(sf org auth show-access-token -o jaselg@reform.org.il --json | jq -j '.result.accessToken')
	if [ -f "$REAL_PATH/.env" ]; then
		sed -i "/SF_TOKEN/s/=.*/=$SF_TOKEN/" "$REAL_PATH/.env"
	else
		echo "SF_TOKEN=$SF_TOKEN" > $REAL_PATH/.env
	fi
}

hrs_elapsed() {
	local seconds_elapsed=$(( $2 - $1 ))
	echo $(( seconds_elapsed / 3600 ))
}

usage() {
	echo "usage: $0 <file: soql query>..." >&2
	echo "$2" >&2
	exit $1
}

[ ! -d "$REAL_PATH/.data/join-components" ] && mkdir -p "$REAL_PATH/.data/join-components"

if [ ! -f "$REAL_PATH/.env" ]; then
	printf "$PRINTFMT" "API Token missing. Creating: "
	time init_token
fi 

# Refresh token if inactive for over two hours
if (( $(hrs_elapsed $(stat --printf "%X" "$REAL_PATH/.env") $(date +"%s")) > 2 )); then
	printf "$PRINTFMT" "API Token expired. Refreshing: "
	time init_token	
fi

source "$REAL_PATH/.env"
declare -a job_stack
declare -a job_state
declare -A query_map

job_state=(
	"JobComplete"
	"InProgress"
	"UploadComplete"
	"Aborted"
	"Failed"
)

query_map=(
	[Contact]="contact-join"
	[Account]="acct-join"
	[npe5__Affiliation__c]="affiliation-join"
)

# Exit with error unless script arguments exist in queries dir
for arg in "$@"; do 
	if [ ! -f "$REAL_PATH/queries/$arg.soql" ]; then
		usage 1 "$arg.soql not found in $REAL_PATH/queries"
	fi
done

# Loop over SOQL queries in queries dir, create jobs and push job ids to stack
for arg in "$@"; do
	query="$REAL_PATH/queries/$arg.soql"
	printf "$PRINTFMT" "Creating query job with ${query#$REAL_PATH}: " 
	time curr_id=$("$REAL_PATH/create_query.pl" $SF_TOKEN $query)
	job_stack+=( "$curr_id" )
done

# Check each id in stack and test exit code to determine whether to download results
while true; do
	limit=${#job_stack[@]}

	for (( i=0; i < $limit; i++ )); do
		printf "$PRINTFMT" "Checking job ${job_stack[$i]}: "
		time obj_type=$($REAL_PATH/check_status.pl $SF_TOKEN ${job_stack[$i]}) 
		exit_code=$?

		echo -e "\tJob state is ${job_state[$exit_code]}"  
		if [ $exit_code -eq 0 ]; then
			file="$REAL_PATH/.data/join-components/${query_map[$obj_type]}.src.csv"
			printf "\t${PRINTFMT/$SPACING/$(( SPACING - 8 ))}" "Saving $obj_type query results to ${file#$REAL_PATH/}: "
			time ("$REAL_PATH/fetch_results.pl" $SF_TOKEN ${job_stack[$i]} > "$file")
			unset 'job_stack[i]'
		fi
	done

	if [ ${#job_stack[@]} -eq 0 ]; then
		break
	fi

	# Still jobs in the stack. Remove empty indices and sleep before next check
	temp_arr=( ${job_stack[@]} ) && job_stack=( ${temp_arr[@]} )
	sleep $SLEEP
done
